style = "blue"
margin = 100
remove_extra_newlines = true
short_to_long_function_def = true
format_docstrings = true
verbose = true
pipe_to_function_call = false
always_for_in = false
always_use_return = false
separate_kwargs_with_semicolon = false
