name = "Sniper"
uuid = "81691e93-b409-492d-a237-cd8ca34c3e3f"
authors = [
	"Mario Dagrada <mario.dagrada@pasqal.com>",
	"Sebastian Grijalva <sebastian.grijalva@pasqal.com>",
	"Niklas Heim <heim.niklas@gmail.com>",
	"Louis Vignoli <louis.vignoli@pasqal.com>",
]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
