name: Documenter
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

jobs:
  Documenter:
    permissions:
      contents: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: julia-actions/setup-julia@v1
       with:
         version: '1'
     - run: |
         julia --project=docs -e '
           using Pkg
           Pkg.instantiate()'
     - run: julia --project=docs --color=yes docs/make.jl
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
